# Generated by Django 3.1.5 on 2021-02-23 03:16

from django.db import migrations


class Migration(migrations.Migration):
    atomic = False  # 添加atomic
    dependencies = [
        ('unesco', '0002_auto_20210223_0243'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='State',
            new_name='States',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='category',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='iso',
            old_name='iso',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='region',
            old_name='region',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='states',
            old_name='state',
            new_name='name',
        ),
    ]
