# Generated by Django 3.1.5 on 2021-02-23 03:29

from django.db import migrations


class Migration(migrations.Migration):
    atomic = False
    dependencies = [
        ('unesco', '0003_auto_20210223_0316'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='States',
            new_name='State',
        ),
    ]
